# Generated by Django 4.1 on 2022-08-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtcase",
            name="entity",
            field=models.TextField(blank=True, default=""),
        ),
    ]
