# Generated by Django 4.1 on 2022-08-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ner", "0002_courtcase_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("document", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
